// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PfProj.Helpers;

#nullable disable

namespace PfProj.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240805194242_CharacterCreationPlusClassInitial")]
    partial class CharacterCreationPlusClassInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PfProj.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("characterClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("currentHitPoints")
                        .HasColumnType("int");

                    b.Property<int?>("dex")
                        .HasColumnType("int");

                    b.Property<int?>("experience")
                        .HasColumnType("int");

                    b.Property<int?>("gold")
                        .HasColumnType("int");

                    b.Property<int?>("level")
                        .HasColumnType("int");

                    b.Property<int?>("magic")
                        .HasColumnType("int");

                    b.Property<int?>("magicResist")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("str")
                        .HasColumnType("int");

                    b.Property<int?>("wis")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("PfProj.Entities.CharacterClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("baseScore")
                        .HasColumnType("int");

                    b.Property<string>("className")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dex")
                        .HasColumnType("int");

                    b.Property<int>("magic")
                        .HasColumnType("int");

                    b.Property<int>("magicResist")
                        .HasColumnType("int");

                    b.Property<int>("str")
                        .HasColumnType("int");

                    b.Property<int>("wis")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CharacterClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
